---
# Project Information
site_name: DataMiner
site_author: Geemi Wellawatte
site_description: A package to generate datasets from academic literature

# Repository information
repo_name: geemi725/litminer
repo_url: https://github.com/geemi725/litminer
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Geemi Wellawatte

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geemi725
      name: geemi725 on GitHub

# Page tree
nav:
  - Home: index.md
